// auto generated by: scim-sdk-schema-pojo-creator
package org.castle.djames.scimforge.api.resources;

import java.time.Instant;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;

import de.captaingoldfish.scim.sdk.common.resources.ResourceNode;
import de.captaingoldfish.scim.sdk.common.resources.base.ScimObjectNode;
import de.captaingoldfish.scim.sdk.common.resources.complex.Meta;



/**
 * User resource
 */
public class User extends ResourceNode
{

  public User()
  {
    setSchemas(Arrays.asList(FieldNames.SCHEMA));
  }

  public User(String id,
              Meta meta,
              String userName,
              Name name,
              String emails,
              List<Entitlements> entitlements)
  {
    setSchemas(Arrays.asList(FieldNames.SCHEMA));
    setId(id);
    setMeta(meta);
    setUserName(userName);
    setName(name);
    setEmails(emails);
    setEntitlements(entitlements);
  }

  /**
   * Unique identifier for the User, typically used by the user to directly authenticate to the service provider.
   */
  public String getUserName()
  {
    return getStringAttribute(FieldNames.USERNAME).get();
  }

  /**
   * Unique identifier for the User, typically used by the user to directly authenticate to the service provider.
   */
  public void setUserName(String userName)
  {
    setAttribute(FieldNames.USERNAME, userName);
  }

  /**
   * The components of the User's real name.
   */
  public Optional<Name> getName()
  {

    return getObjectAttribute(FieldNames.NAME, Name.class);
  }

  /**
   * The components of the User's real name.
   */
  public void setName(Name name)
  {
    setAttribute(FieldNames.NAME, name);
  }

  /**
   * Email address for the User.
   */
  public String getEmails()
  {
    return getStringAttribute(FieldNames.EMAILS).get();
  }

  /**
   * Email address for the User.
   */
  public void setEmails(String emails)
  {
    setAttribute(FieldNames.EMAILS, emails);
  }

  /**
   * A list of entitlements for the User.
   */
  public List<Entitlements> getEntitlements()
  {
    return getArrayAttribute(FieldNames.ENTITLEMENTS, Entitlements.class);  }

  /**
   * A list of entitlements for the User.
   */
  public void setEntitlements(List<Entitlements> entitlements)
  {
    setAttribute(FieldNames.ENTITLEMENTS, entitlements);
  }


  /**
   * The components of the User's real name.
   */
  public static class Name extends ScimObjectNode
  {
    public Name()
    {
    }

    public Name(String firstName,
                String lastName)
    {
      setFirstName(firstName);
      setLastName(lastName);
    }

    /**
     * The first name of the User.
     */
    public Optional<String> getFirstName()
    {
      return getStringAttribute(FieldNames.FIRSTNAME);
    }

    /**
     * The first name of the User.
     */
    public void setFirstName(String firstName)
    {
      setAttribute(FieldNames.FIRSTNAME, firstName);
    }

    /**
     * The last name of the User.
     */
    public Optional<String> getLastName()
    {
      return getStringAttribute(FieldNames.LASTNAME);
    }

    /**
     * The last name of the User.
     */
    public void setLastName(String lastName)
    {
      setAttribute(FieldNames.LASTNAME, lastName);
    }

  }

  /**
   * A list of entitlements for the User.
   */
  public static class Entitlements extends ScimObjectNode
  {
    public Entitlements()
    {
    }

    public Entitlements(String appId,
                        String appName,
                        String value)
    {
      setAppId(appId);
      setAppName(appName);
      setValue(value);
    }

    /**
     * The identifier for the application.
     */
    public Optional<String> getAppId()
    {
      return getStringAttribute(FieldNames.APPID);
    }

    /**
     * The identifier for the application.
     */
    public void setAppId(String appId)
    {
      setAttribute(FieldNames.APPID, appId);
    }

    /**
     * The name of the application.
     */
    public Optional<String> getAppName()
    {
      return getStringAttribute(FieldNames.APPNAME);
    }

    /**
     * The name of the application.
     */
    public void setAppName(String appName)
    {
      setAttribute(FieldNames.APPNAME, appName);
    }

    /**
     * The value of the entitlement.
     */
    public Optional<String> getValue()
    {
      return getStringAttribute(FieldNames.VALUE);
    }

    /**
     * The value of the entitlement.
     */
    public void setValue(String value)
    {
      setAttribute(FieldNames.VALUE, value);
    }

  }

  /**
   * contains the attribute names of the resource representation
   */
  public static class FieldNames
  {

    public static final String SCHEMA = "urn:custom:params:scim:schemas:djamescastle:1.0:User";

    public static final String USERNAME = "userName";
    public static final String NAME = "name";

    public static final String FIRSTNAME = "firstName";

    public static final String LASTNAME = "lastName";
    public static final String EMAILS = "emails";
    public static final String ENTITLEMENTS = "entitlements";

    public static final String APPID = "appId";

    public static final String APPNAME = "appName";

    public static final String VALUE = "value";
  }
}
