version: '3'
services:
  scim-forge-postgres:
    image: postgres:alpine3.19
    hostname: scim-forge-postgres
    container_name: scim-forge-postgres
    volumes:
      - ./postgres/initdb/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -p 1234
      interval: 10s
      timeout: 5s
      retries: 5

  scim-forge-zookeeper:
    image: confluentinc/cp-zookeeper:${KAFKA_VERSION}
    hostname: scim-forge-zookeeper
    container_name: scim-forge-zookeeper
    ports:
      - "22181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: WARN
      ZOOKEEPER_SERVER_CNXN_FACTORY: "org.apache.zookeeper.server.NettyServerCnxnFactory"

  scim-forge-kafka:
    image: confluentinc/cp-kafka:${KAFKA_VERSION}
    hostname: scim-forge-kafka
    container_name: scim-forge-kafka
    depends_on:
      - scim-forge-zookeeper
    ports:
      - "29092:29092"
      - "29093:29093"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://scim-forge-kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_BROKER_ID: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_KAFKASTORE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: scim-forge-zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG4J_LOGGERS: "org.apache.zookeeper=WARN,state.change.logger=WARN,kafka.producer.async.DefaultEventHandler=WARN,kafka.controller=WARN,kafka=WARN"
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
    healthcheck:
      test: kafka-topics --bootstrap-server localhost:29092 --list
      interval: 30s
      timeout: 10s
      retries: 3

  scim-forge-schema-registry:
    image: confluentinc/cp-schema-registry:${KAFKA_VERSION}
    container_name: scim-forge-schema-registry
    depends_on:
      - scim-forge-zookeeper
      - scim-forge-kafka
    ports:
      - "7081:7081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: scim-forge-schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "scim-forge-kafka:9092"
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "scim-forge-zookeeper:2181"
      SCHEMA_REGISTRY_KAFKASTORE_REPLICATION_FACTOR: 1
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:7081"
      SCHEMA_REGISTRY_LOG4J_LOGGERS: "org.apache.kafka=WARN,org.apache.zookeeper=WARN"
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: WARN
      SCHEMA_REGISTRY_REPLICATION_FACTOR: 1
    healthcheck:
      test: curl --output /dev/null --silent --head --fail http://localhost:7081/subjects
      interval: 30s
      timeout: 30s
      retries: 3





